.\" t
.TH GIDEAL @MAN1EXT@ "@MDATE@" "Groff Version @VERSION@"
.SH NAME
gideal \(em \fIgroff\fP preprocessor for the \fIideal\fP language
.
.\" The .SH was moved to this place in order to appease `apropos'.
.
.\" gideal.1 - man page for the ideal roff preprocessor
.\" Source file position:  <groff_source_top>/contrib/gideal/gideal.man
.\" Installed position:    $prefix/share/man/man1/gideal.1
.
.
.\" --------------------------------------------------------------------
.\" Legalese
.\" --------------------------------------------------------------------
.
.de co
Copyright \[co] 2014 Free Software Foundation, Inc.

This file is part of gideal, which is part of groff, a free software
project.

You can redistribute it and/or modify it under the terms of the GNU
General Public License version 2 (GPL2), as published by the Free
Software Foundation.

The license text is available in the internet at
.UR http://\:www.gnu.org/\:licenses/\:gpl-2.0.html
.UE .
..
.
.de au
This file was written by
.MT bernd.warken@web.de
Bernd Warken
.ME .
..
.
.\" --------------------------------------------------------------------
.\" Characters
.\" --------------------------------------------------------------------
.
.\" Ellipsis ...
.ie t .ds EL \fS\N'188'\fP
.el .ds EL \&.\|.\|.\&\
.\" called with \*(EL
.
.\" Bullet
.ie t .ds BU \(bu
.el .ds BU *
.\" used in `.IP \*(BU 2m' (former .Topic)
.
.
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.
.SY gideal
.OP \-
.OP \-\-
.OP \fI\%filespec \*(EL
.YS
.
.BR "gideal \-h" | "\-\-help"
.br
.BR "gideal \-v" | "\-\-version"
.
.
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.
.P
.B gideal
is a
.I groff preprocessor
for using the roff language
.BR ideal (@MAN7EXT@)
for drawing pictures within
.I groff files
(to be done).
.
.
.\" --------------------------------------------------------------------
.SH OPTIONS
.\" --------------------------------------------------------------------
.
In
.BR gideal ,
there are the following kinds of options:
.IP \*(BU 2m
.I breaking options
.IP \*(BU 2m
.I filespec options
.
.
.\" --------------------------------------------------------------------
.SS "Breaking Options"
.\" --------------------------------------------------------------------
.
.I Breaking options
are used to display a corresponding information, but then the whole
program run is stopped and finished.
.
.
.P
The breaking options
.B \-v
or
.B \-\-version
print information on the version number.
.
.
.P
The breaking options
.B \-h
or
.B \-\-help
print usage information.
.
.
.P
Both of these options automatically end the program.
.
Other options are then ignored.
.
.
.\" --------------------------------------------------------------------
.SS "Filespec Options"
.\" --------------------------------------------------------------------
.
Each argument that does not start with a minus
.B \-
character is interpreted as a file name.
.
.
.P
As usual, the single minus character argument
.B \-
means to integrate
.IR "standard input" .
.
.
.P
The double minus
.B \-\-
argument means noting special by itself, but means that all following
arguments will be interpreted as file names, even if it starts with a
minus
.B \-
character.
.
.
.\" --------------------------------------------------------------------
.SH HISTORY
.\" --------------------------------------------------------------------
.
The roff language
.BR ideal (@MAN7EXT@)
was invented by
.I Christopher J. Wyk
in 1981 at AT&T.
.
.
.P
Moreover, a roff preprocessor for this language with the name
.B ideal
was invented by the same programmer as well, but this preprocessor
looks now quite old-fashioned.

.
There is now a complitely new preprocessor for the groff system in
development.
.
It will be called
.BR gideal (@MAN1EXT@),
other than the original preprocessor.
.
.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
.\" --------------------------------------------------------------------
.
.TP
.B Unix8 preprocessor
freely available documentation for the
.IR "ideal preprocessor" .
.
The
.I preprocessor
there is called
.BR ideal ,
not
.B gideal
as in
.IR groff .
.br
.UR http://man.cat-v.org/unix_8th/1/ideal
.UE .
.
.
.\" --------------------------------------------------------------------
.SH "COPYING"
.\" --------------------------------------------------------------------
.co
.\" --------------------------------------------------------------------
.SH "AUTHORS"
.\" --------------------------------------------------------------------
.au
.
.
.\" --------------------------------------------------------------------
.\" Emacs settings
.\" --------------------------------------------------------------------
.
.\" Local Variables:
.\" mode: nroff
.\" End:
