.TH IDEAL @MAN7EXT@ "@MDATE@" "Groff Version @VERSION@"
.SH NAME
ideal \[em] the groff \fIideal\fP language
.
.\" The .SH was moved to this place in order to appease `apropos'.
.
.\" ideal.7 - man page for the ideal roff language

.\" Source file position:  <groff_source_top>/contrib/gideal/ideal.man
.\" Installed position:    $prefix/share/man/man7/ideal.7
.
.
.\" --------------------------------------------------------------------
.\" Legalese
.\" --------------------------------------------------------------------
.
.de co
Copyright \[co] 2014 Free Software Foundation, Inc.

This file is part of ideal and gideal, which is part of groff, a free
software project.

You can redistribute it and/or modify it under the terms of the GNU
General Public License version 2 (GPL2) as published by the Free
Software Foundation.

The license text is available in the internet at
.UR http://www.gnu.org/licenses/gpl-2.0.html
.UE .
..
.
.de au
This file was written by
.MT bernd.warken@web.de
Bernd Warken
.ME .
..
.
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.
.I ideal
is a
.I roff
language for drawing pictures.
.
.BR gideal (@MAN1EXT@)
will be the corresponding
.I groff
preprocessor for using this language within groff files.
.
.
.\" --------------------------------------------------------------------
.SH "IDEAL PARTS"
.\" --------------------------------------------------------------------
.
Within a roff file, an
.I ideal part
is started with the command
.B .IS
and is ended with one of the commands
.B .IE
or
.BR .IF .
.
.
.P
The text between these opening and closing requests is handled by the
preprocessor
.BR gideal .
.
By that the
.I ideal part
is transformed into
.IR "pic content" ,
which can be read with the graphical groff preprocessor
.BR pic (@MAN1EXT@).
.
.
.\" --------------------------------------------------------------------
.SH HISTORY
.\" --------------------------------------------------------------------
.
The roff preprocessor and the roff language
.I ideal
were invented by
.I Christopher J. Wyk
in 1981 at AT&T.
.
.
.P
The
.I ideal language
is based on
.IR "complex numbers" .
.
These are well documented at the documentation of the
.UR http://\:search.cpan.org/\:~zefram/\:Math-Complex-1.59/\:lib/\:Math\
/\:Complex.pm
Math::Complex Perl package
.UE .
.
This documentation is more about the complex mathematics, but also a
bit about related Perl examles.
.
.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
.\" --------------------------------------------------------------------
.
.\" --------------------------------------------------------------------
.SS "libfiles"
.\" --------------------------------------------------------------------
.
.I libfiles
were files written in
.IR ideal ,
that could be included into roff files with the command
.BR ...libfile .
.
They are now obsolete because of license problems.
.
.
.\" --------------------------------------------------------------------
.SS "Examples"
.\" --------------------------------------------------------------------
.
It is planned to add some roff files with included
.I ideal parts
as examples into the source subdirectory
.BR files.
.
They will then be installed into
.BR @EXAMPLEDIR@/ideal .
.
.
.\" --------------------------------------------------------------------
.SS "Man-Pages"
.\" --------------------------------------------------------------------
.
.TP
.BR gideal (@MAN1EXT@)
for information about the
.I ideal
preprocessor in
.IR groff .
.
.
.TP
.BR pic (@MAN1EXT@)
The
.I ideal
parts will be translated into
.I pic
roff language.
.
.
.\" --------------------------------------------------------------------
.SS "Documentation and Articles"
.\" --------------------------------------------------------------------
.
.TP
.B ACM articles for buying
.
.RS
.
.TP
.B p99-van_wyk.pdf.gz
.nf
A Graphics Typesetting Language
Christopher J. Van Wyk
.fi
.UR http://dl.acm.org/citation.cfm?id=806460
.UE
.
.TP
.B p163-van_wyk.pdf.gz
.nf
A High-Level Language for Specifying Pictures
Christopher J. Van Wyk
.fi
.UR http://dl.acm.org/citation.cfm?id=357303
.UE
.
.RE
.
.
.\" --------------------------------------------------------------------
.SH "COPYING"
.\" --------------------------------------------------------------------
.co
.\" --------------------------------------------------------------------
.SH "AUTHORS"
.\" --------------------------------------------------------------------
.au
.
.
.\" --------------------------------------------------------------------
.\" Emacs settings
.\" --------------------------------------------------------------------
.
.\" Local Variables:
.\" mode: nroff
.\" End:
