.\" t
.TH IDEAL @MAN7EXT@ "@MDATE@" "Groff Version @VERSION@"
.SH NAME
ideal \[em] the groff \f[I]ideal\f[] language
.
.\" The .SH was moved to this place in order to appease `apropos'.
.
.\" --------------------------------------------------------------------
.\" Legalese
.\" --------------------------------------------------------------------
.
.ig
ideal.7 - man page for the ideal roff language
.
Source file position:  <groff_source_top>/contrib/gideal/ideal.man
Installed position:    $prefix/share/man/man7/ideal.7
.
Last update: 4 Jul 2014
..
.
.de authors
This file was written by Bernd Warken
.MT bernd.warken@web.de
.ME .
..
.
.de copying
Copyright \(co 2014
.RS
.ft CI
Free Software Foundation, Inc.
.ft R
.RE
.
.P
This file is part of
.IR \%ideal ,
which is part of
.IR \%groff ,
a free software project.
.
You can redistribute it and/or modify it under the terms of the
.nh
.ft CI
GNU General Public License
.ft R
.hy
as published by the
.nh
.ft CI
Free Software Foundation version\~2
.ft R
.hy
(\\f[CI]GPL2\\f[R]).
.
.P
The license text is available in the internet at
.UR http://www.gnu.org/licenses/gpl-2.0.html
.UE .
..
.
.
.\" --------------------------------------------------------------------
.\" Setup
.\" --------------------------------------------------------------------
.
.\" --------------------------------------------------------------------
.\" Characters
.\" --------------------------------------------------------------------
.
.ie t .char \[Ellipsis] \f[S]\N'188'\f[P]
.el .char \[Ellipsis] \f[I]...\f[P]
.\" called by \[Ellipsis]
.
.
.\" --------------------------------------------------------------------
.\" Macro definitions
.\" --------------------------------------------------------------------
.
.\" --------------------------------------------------------------------
.\" .Error  (<text>...)
.\"
.\" Print error message to terminal and abort.
.\"
.de Error
.  tm \\$*
.  ab
..
.
.\" --------------------------------------------------------------------
.\" .FONT (<font name> <text> [<font name> <text> ...])
.\"
.\"  in different fonts: R, I, B, CR, CI, CB
.\"
.de FONT
.  if (\\n[.$] = 0) \{\
.	\" compatibility to .ft
.	nop \&\f[P]\&
.	return
.  \}
.  ds result \&
.  while (\\n[.$] >= 2) \{\
.	as result \,\f[\\$1]\\$2
.	if !"\\$1"P" .as result \f[P]
.       \" the double-quote " after P above is now ignored in Emacs
.	shift 2
.  \}
.  if (\\n[.$] = 1) .as result \,\f[\\$1]
.\"  nh
.  nop \\*[result]\&
.\"  hy
.  rm result
..
.
.\"  --------------------------------------------------------------------
.\" .Text  (<text>...)
.\"
.\" Treat the arguments as text, no matter how they look.
.\"
.de Text
.  if \\n[.$]=0 \
.    return
.  nh
.  nop \)\\$*\)
.  hy
..
.
.\" --------------------------------------------------------------------
.\" .Topic  ([<indent>])
.\"
.\" A bulleted paragraph
.\"
.de Topic
.  ie \\n[.$]=0 .ds @indent 2m\"
.  el .ds @indent \\$1\"
.
.  ie t .IP \[bu] \\*[@indent]
.  el .IP \- \\*[@indent]
.
.  rm @indent
..
.
.\" --------------------------------------------------------------------
.\" .UNDERLINE (<text to underline> [<append>])
.\"
.\" Underline $1 and append $2 without underline
.\"
.de UNDERLINE
.  ie n \fI\\$1\fP\\$2
.  el \Z'\\$1'\v'.25m'\D'l \w'\\$1'u 0'\v'-.25m'\\$2
..
.
.\" end of macro definitions
.\" --------------------------------------------------------------------
.
.
.\" --------------------------------------------------------------------
.SH DESCRIPTION
..\" --------------------------------------------------------------------
.
.BR ideal (@MAN7EXT@)
is a
.I roff
language for drawing pictures.
.
.BR gideal (@MAN1EXT@)
is the corresponding
.I groff
preprocessor for using this language within
.I groff files
(to be done).
.
.
.\" --------------------------------------------------------------------
.SH "IDEAL PARTS"
.\" --------------------------------------------------------------------
.
Within a roff file, an
.I ideal part
is started with the command
.BR .IS .
.
.
.P
this part is ended with the command
.B .IE
or
.BR .IF .
.
.
.P
The text between these requests is handled by the preprocessor
.BR gideal (@MAN1EXT@).
.
.
.\" --------------------------------------------------------------------
.SH HISTORY
.\" --------------------------------------------------------------------
.
The roff preprocessor and the roff language
.I ideal
were invented by
.I Christopher J. Wyk
in 1981 at AT&T.
.
.
.P
The
.I ideal language
is based on
.IR "complex numbers" .
.
These are well documented at the documentation of the
.UR http://\:search.cpan.org/\:~zefram/\:Math-Complex-1.59/\:lib/\:Math\
/\:Complex.pm
Math::Complex Perl package
.UE .
.
This documentation is more about the complex mathematics, but also a
bit about related Perl examles.
.
.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
.\" --------------------------------------------------------------------
.
.\" --------------------------------------------------------------------
.SS "libfiles"
.\" --------------------------------------------------------------------
.
.I libfiles
are file written in
.IR ideal .
.
Such a file can be included into a roff file with
.I ideal parts
by the ideal command
.BR ...libfile .
.
A
.I libfile
can also serve as an example.
.
.
.P
With the installation, the available
.I libfiles
will get into
.B @DATASUBDIR@/ideal/libfiles
.
.
.\" --------------------------------------------------------------------
.SS "Examples"
.\" --------------------------------------------------------------------
.
Some
.I roff
files with included 
.I ideal parts
will be stored at the installation into
.BR @EXAMPLEDIR@/ideal .
.
.
.\" --------------------------------------------------------------------
.SS "Man-Pages"
.\" --------------------------------------------------------------------
.
.TP
.BR gideal (@MAN1EXT@)
for information about the
.I ideal
preprocessor in
.IR groff .
.
.
.TP
.BR groff (@MAN1EXT@),
.TQ
.BR groff (@MAN7EXT@),
.TQ
.BR grog (@MAN1EXT@),
.TQ
.BR pic (@MAN1EXT@),
.TQ
.BR gpic (@MAN1EXT@),
.TQ
Information about the
.I groff
system.
.
.
.\" --------------------------------------------------------------------
.SS "Documentation and Articles"
.\" --------------------------------------------------------------------
.
.TP
.B Unix8 preprocessor
freely available documentation for the
.IR "ideal preprocessor" .
.
The
.I preprocessor
there is called
.BR ideal ,
not
.B gideal
as in
.IR groff .
.br
.UR http://man.cat-v.org/unix_8th/1/ideal
.UE .
.
.
.TP
.B ACM articles for buying
.
.RS
.
.TP
.B p99-van_wyk.pdf.gz
.nf
A Graphics Typesetting Language
Christopher J. Van Wyk
.fi
.UR http://dl.acm.org/citation.cfm?id=806460
.UE
.
.TP
.B p163-van_wyk.pdf.gz
.nf
A High-Level Language for Specifying Pictures
Christopher J. Van Wyk
.fi
.UR http://dl.acm.org/citation.cfm?id=357303
.UE
.
.RE
.
.
.\" --------------------------------------------------------------------
.SH "AUTHORS"
.\" --------------------------------------------------------------------
.
.authors
.
.
.\" --------------------------------------------------------------------
.SH "COPYING"
.\" --------------------------------------------------------------------
.
.copying
.
.
.\" --------------------------------------------------------------------
.\" Emacs settings
.\" --------------------------------------------------------------------
.
.\" Local Variables:
.\" mode: nroff
.\" End:
