all: prepare_examples

prepare_examples:
	if test ! -f gnu.eps; then \
	  if test -f $(top_srcdir)/doc/gnu.eps; then \
	    cp $(top_srcdir)/doc/gnu.eps . ; \
	  else \
	    cp $(top_builddir)/doc/gnu.eps . ; \
	  fi ; \
	fi
