MAN1=grap2graph.n
CLEANADD=grap2graph

all: grap2graph

grap2graph: grap2graph.sh
	rm -f $@; \
	sed -e "s|@g@|$(g)|g" \
	    -e "s|@VERSION@|$(version)$(revision)|" \
	    -e $(SH_SCRIPT_SED_CMD) $(srcdir)/grap2graph.sh >$@; \
	chmod +x $@

install_data: grap2graph
	-test -d $(DESTDIR)$(bindir) || $(mkinstalldirs) $(DESTDIR)$(bindir)
	-rm -f $(DESTDIR)$(bindir)/grap2graph
	$(INSTALL_SCRIPT) grap2graph $(DESTDIR)$(bindir)/grap2graph

uninstall_sub:
	-rm -f $(DESTDIR)$(bindir)/grap2graph
