.ig
groffer.man

Version     : groffer 0.5 (beta)
Last update : 08 Jan 2002

This file is part of groff, the GNU roff type-setting system.

Copyright (C) 2001, 2002 Free Software Foundation, Inc.
Written by Bernd Warken <bwarken@mayn.de>

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with the
Invariant Sections being this .ig-section and AUTHORS, with no
Front-Cover Texts, and with no Back-Cover Texts.

A copy of the Free Documentation License is included as a file called
FDL in the main directory of the groff source package.
..
.
.\" --------------------------------------------------------------------
.\" Setup
.\" --------------------------------------------------------------------
.
.mso www.tmac
.
.if n \{\
.  mso tty-char.tmac
.  ftr CR R
.  ftr CI I
.  ftr CB B
.\}
.
.if '\*[.T]'dvi' \{\
.  ftr CB CW
.\}
.
.ie t \{\
.  ds @- "\-\"
.  ds @-- "\-\-\" 
.\}
.el \{\
.  ds @- "-\"
.  ds @-- "--\" 
.\}
.
.ds Ellipsis .\|.\|.\"
.
.\" --------------------------------------------------------------------
.\" Start macro definitions
.eo
.
.de c
.\" this is like a comment request when escape mechanism is off
..
.c  --------------------------------------------------------------------
.de Text
.  nop \)\$*
..
.c --------------------------------------------------------------------
.c environment variable
.de EnvVar
.  nh
.  BR \$1 \$2
.  hy
..
.c --------------------------------------------------------------------
.c LongOpt  ([name [punct]])
.c
.c `--name' somwhere in the text 
.c second arg is punctuation
.c
.de LongOpt
.  ds @opt \$1\"
.  shift
.  nh
.  Text \f[CB]\*[@--]\f[P]\f[B]\*[@opt]\f[P]\/\$*
.  hy
.  rm @opt
..
.c --------------------------------------------------------------------
.c [LongOpt]  (name [arg])
.c
.c long option in synopsis
.c
.de [LongOpt]
.  if (\n[.$] == 0) \
.    return
.  ds @opt \$1\"
.  shift
.  nh
.  ie (\n[.$] == 0) \
.    Text \f[R][\f[P]\f[CB]\*[@--]\f[P]\f[B]\*[@opt]\f[P]\f[R]]\f[P]
.  el \{\
.    Text \f[R][\f[P]\f[CB]\*[@--]\f[P]\f[B]\*[@opt]
.    Text \f[P]\f[I]\/\$*\f[P]\f[R]]\f[P]
.  \}
.  hy
.  rm @opt
..
.c --------------------------------------------------------------------
.c OptDef  (shortopt [longopt [argument]])
.c
.c option documentation
.c args : `shortopt', `longopt' can be ""
.c
.de OptDef
.  rm @short
.  rm @long
.  rm @arg
.  nh
.  if (\n[.$] >= 1) \{\
.    ds @1 \$1\"
.    if !'\*[@1]'' \
.      ds @short \f[CB]\*[@-]\*[@1]\f[P]\"
.    if (\n[.$] >= 2) \{\
.      if !'\*[@short]'' \
.        as @short \f[CW]\0\f[P]\"
.      ds @2 \$2\"
.      if !'\*[@2]'' \
.        ds @long \f[CB]\*[@--]\f[P]\f[B]\*[@2]\f[P]\"
.      if (\n[.$] >= 3) \{\
.        if !'\*[@long]'' \
.          as @long \|=\|\"
.        shift 2
.        ds @arg \fI\$*\"
.      \}
.    \}
.  \}
.  IP "\f[R]\*[@short]\*[@long]\*[@arg]\f[P]"
.  hy
.  rm @1
.  rm @2
.  rm @arg
.  rm @short
.  rm @long
..
.c --------------------------------------------------------------------
.c a shell command line
.de ShellCommand
.  br
.  ad l
.  nh
.  Text \f[I]shell#\h'1m'\f[P]\f[CR]\$*\f[P]\&\"
.  ft R
.  ft P
.  hy
.  ad
..
.c --------------------------------------------------------------------
.c ShellLongOpt  ([name])
.c
.c `--name' in a shell command
.c second arg is punctuation
.c
.de ShellLongOpt
.  ds @1 \$1\"
.  shift
.  Text \*[@--]\*[@1]
.  rm @1
..
.c --------------------------------------------------------------------
.c ShellShortOpt ([char])
.c
.c `-c' somwhere in the text 
.c second arg is punctuation
.c
.de ShellShortOpt
.  ds @1 \$1\"
.  shift
.  Text \*[@-]\*[@1]
.  rm @1
..
.c --------------------------------------------------------------------
.c ShortOpt ([char [punct]])
.c
.c `-c' somwhere in the text 
.c second arg is punctuation
.c
.de ShortOpt
.  ds @opt \$1\"
.  shift
.  nh
.  Text \f[CB]\*[@-]\f[P]\f[B]\*[@opt]\fP\/\$*
.  hy
.  rm @opt
..
.c --------------------------------------------------------------------
.c [ShortOpt]  (name [arg])
.c
.c short option in synopsis
.c
.de [ShortOpt]
.  if (\n[.$] == 0] \
.    return
.  ds @opt \$1\"
.  shift
.  nh
.  ie (\n[.$] == 0) \
.    Text \f[R][\f[P]\f[CB]\*[@-]\*[@opt]\f[P]\f[R]]\f[P]
.  el \{\
.    Text \f[R][\f[P]\f[CB]\*[@-]\*[@opt]
.    Text \f[P]\f[I]\/\$*\f[P]\f[R]]\f[P]
.  \}
.  hy
.  rm @opt
..
.c --------------------------------------------------------------------
.de Synopsis
.  nh
.  ds @1 \$1\"
.  nr @old_indent \n(.i
.  ad l
.  in +\w'\fB\*[@1]\0'u
.  ti \n[@old_indent]u
.  B \*[@1]\0\c
.  rr @old_indent
.  rm @1
..
.de EndSynopsis
.  br
.  ad
.  in
.  hy
..
.c --------------------------------------------------------------------
.c Topic
.c
.c a bulleted paragraph
.c
.de Topic
.  TP 2m
.  Text \[bu]
..
.c --------------------------------------------------------------------
.c Extends .TP header
.de TP+
.  br
.  ns
.  TP \$1
..
.ec
.\" End of macro definitions
.
.
.\" --------------------------------------------------------------------
.\" Title
.\" --------------------------------------------------------------------
.
.TH GROFFER @MAN1EXT@ "@MDATE@" "Groff Version @VERSION@"
.SH NAME
groffer \- display groff files and man\~pages on X and tty
.
.
.\" --------------------------------------------------------------------
.SH "SYNOPSIS"
.\" --------------------------------------------------------------------
.
.ad l
.Synopsis groffer
.[ShortOpt] Q
.[ShortOpt] T device
.[ShortOpt] W arg
.[LongOpt] dpi resolution
.[LongOpt] man
.[LongOpt] manpath man_page_dirs
.[LongOpt] no\*[@-]man
.[LongOpt] title "'title in X mode'"
.[LongOpt] tty
.[LongOpt] xrdb X_resouce_options
.RI [ groff_options ]
.RI [ filespec
.Text \*[Ellipsis]]
.EndSynopsis
.
.Synopsis groffer
.ShortOpt h
|
.LongOpt help
.EndSynopsis
.
.Synopsis groffer
.ShortOpt v
|
.LongOpt version
.EndSynopsis
.
.P
where each element of the
.I filespec
sequence has one of the following forms, where testing is done in the
specified sequence.
.
.TP 10m
.I filename
the path name of an existing file.
.
.TP
.ShortOpt
stands for standard input (can occur several times).
.
.TP
.BI man: name ( section )
search the man\~page
.I name
in
.IR section ,
the same as
.IB name . section
above
.
.TP
.BI man: name . section
the manual page (man\~page)
.I name
in
.IR section ,
see
.BR man (1).
.
.TP
.BI man: name
search the man\~page
.I name
in the lowest section.
.
.TP
.IB name . section
the manual page (man\~page)
.I name
in
.IR section ,
see
.BR man (1).
.
.TP
.BI other_name
if not an existing file search the man\~page
.I other_name
in the lowest section.
.
.P
No
.I filespec
parameters means standard input.
.
.
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.
The
.I groffer
program is able to display files written in the
.IR "roff formatting language" ;
see
.BR roff (@MAN7EXT@)
and
.BR groff (@MAN7EXT@).
When called from within the X window system the input is displayed
using the graphical viewer program
.BR gxditview (@MAN1EXT@),
otherwise text output is displayed in a pager on the terminal.
.
.P
The program always concatenates all input specified by the non-option
parameters of the calling command line, or standard input if none are
given.
.
Compressed standard input or files are decompressed on-the-fly.
.
.P
Moreover, groffer provides a search facility for manual pages
(man\~pages).
.
This makes the groffer program a graphical extension of the
.BR man (1)
program.
.
.P
Normally, the input is run through the
.BR groff (@MAN1EXT@)
text processor before being displayed.
.
By using the option
.ShortOpt Q ,
the roff source code is displayed without being processed.
.
.P
The
.ShortOpt T
option allows to produce output for any output devices provided by
groff.
.
This is like groff, but additionally with the search and decompression
facilities.
.
.P
Internally, the program uses the
.BR grog (@MAN1EXT@)
program to determine from the source which preprocessors should be run
and which macro files should be included.
.
This can be controlled manually by providing suitable options from the
.BR groff (@MAN1EXT@)
program.
.
.
.\" --------------------------------------------------------------------
.SH OPTIONS
.\" --------------------------------------------------------------------
.
If your system does not support GNU long options you can use the
.ShortOpt W
to simulate long options.
.
POSIX has reserved this option for such uses.
.
.P
The following options are caught be groffer and have a special
meaning.
.
.OptDef h help
Print usage message to standard error and exit.
.
.OptDef Q source
Output the roff source code of the input files unprocessed.
.
.OptDef T device devname
Use
.I devname
as the output device, just like in plain groff;
if this is
.B X75
the X output with 75 dpi is selected, with
.B X100
X output will have 100 dpi, which is the default anyway; all other
devices generate output that was processed for the specified device;
this is printed onto standard output without a pager.
.
.OptDef v version
Print version information onto standard error.
.
.OptDef W "" arg
There are 3 applications for the
.ShortOpt W
option:
.br
.ShortOpt W
.I longopt
is equivalent to
.LongOpt longopt
.br
.ShortOpt W
.I 'longopt=arg'
is equivalent to
.LongOpt longopt
.I 'arg'
.br
.ShortOpt W
.I warning
is equivalent to the groff option
.ShortOpt W
.I warning
and is internally sent to groff.
.
.OptDef "" dpi "resolution"
Set resolution of the X viewer.
.
The only supported dpi values are
.B 75
and
.BR 100 .
The writings
.B 75dpi
and
.B 100dpi
are also recognized as a valid argument.
.
.OptDef "" man
Check the non-option command line arguments (filespecs) first on being
man\~pages, then whether they represent an existing file.
.
By default, a filespec is first tested if it is an existing file.
.
.OptDef "" manpath "'dir1 dir2 \*[Ellipsis]'"
.br
.ns
.OptDef "" manpath "'dir1:dir2:\*[Ellipsis]'"
Use the specified search path for retrieving man\~pages instead of the
program defaults.
.
If the argument is set to the empty string "" the search for man\~page
is disabled.
.
.OptDef "" no\*[@-]man
Do not check for man\~pages.
.
.OptDef "" title "'some title of your own'"
Set the title for the diplay window.
.
This effects only the X mode.
.
.OptDef "" tty
Use output on a text pager even when in X.
.
.OptDef "" xrdb "'\*[@-]\fIopt1 arg1\fP \*[@-]\fIopt2 arg2 ...\fP'"
Pass the argument unchanged to the X display program gxditview of
groffer.
.
All options of
.BR gxditview (@MAN1EXT@)
are allowed; this inludes
.ShortOpt bg
(background color),
.ShortOpt display
(the X display to be used),
.ShortOpt geometry
(size and position of the window),
.ShortOpt fg
(foreground color),
.ShortOpt fn
(font),
.ShortOpt xrm
(set general X resource),
and many more, see
.BR X (1).
Several
.LongOpt xrdb
options can be specified or several resource options can be stuffed
into a single
.LongOpt xrdb
option.
.
But note that this is not correctly parsed when the argument for a
resource option contains a space or an embedded single quote character,
even when they are escaped.
.
.TP
.LongOpt		\" just `--'
Signals the end of option processing; all remaining arguments are
interpreted as filespec parameters.
.
.P
Besides these, groffer accepts all arguments that are valid for the
.BR groff (@MAN1EXT@)
program.
.
All non-groffer options are sent unmodified via grog to groff.
.
Postprocessors, macro packages, compatibility with classical troff,
and much more can be manually specified.
.
.
.\" --------------------------------------------------------------------
.SH FEATURES
.\" --------------------------------------------------------------------
.
This chapter describes the details of the features of the groffer
program in detail.
.
.
.\" --------------------------------------------------------------------
.SS "Output modes"
.\" --------------------------------------------------------------------
.
The groffer program provides 4 different operation modes,
.Topic
graphical display in X,
.Topic
text display in a pager,
.Topic
output for a given device streamed onto standard output.
.Topic
source code streamed onto standard output.
.
.P
Normally, the input is processed by groff and then displayed in a
viewer, either in X or on a text terminal.
.
If the environment variable
.EnvVar $DISPLAY
is set or one of the options
.ShortOpt X ,
.ShortOpt TX100 ,
or
.ShortOpt TX75
is set the
.B gxditview
program will be started on the X terminal that is specified by the
.EnvVar $DISPLAY
variable.
.
.P
X provides two resolutions, the old value
.B 75 dpi
and the more modern value of
.BR "100 dpi" ,
which should be available on almost all modern computers.
.
By default, the X resolution of 100 dpi is used if there are
corresponding fonts available; this is checked by questioning the X
font path using the shell command
.ShellCommand xset q
.
.P
The lower resolution can be explicitly specified by the option
.ShortOpt TX75 ;
the option
.ShortOpt X
is inherited from groff, actually it chooses 75 dpi as well.
.
.P
If the variable
.EnvVar $DISPLAY
is not set or empty groffer assumes that it should produce output on a
text terminal.
.
In the actual implementation, the groff output device
.I latin1
is chosen and the processed output is piped into a pager program.
.
The pager (together with options) can be specified by the environment
variable
.EnvVar $PAGER .
If this is not set or empty the
.BR less (1)
program is used as the default pager.
.
.P
Besides the two display modes above, for X and text pager, there are
two more operating modes.
.
These are streaming modes, that means both of them print to standard
output without using a pager.
.
.P
If a device other than the
.B X
devices is specified with the
.ShortOpt T
option groffer assumes that the user wants to pipe the output into
some kind of postprocessor.
.
The reason for this is that the output of many devices, such as
.BR ps ,
or
.B dvi
is not directly displayable.
.
.P
The user may also choose to read the source code of the input by
specifying the
.ShortOpt Q
option.
.
Again, no output pager is used to allow piping.
.
.
.\" --------------------------------------------------------------------
.SS Decompression
.\" --------------------------------------------------------------------
.
The program has a decompression facility.
.
If standard input or a file that is specified as a command line
parameter was compressed by a format that is understood by
.BR gzip (1)
it is decompressed on-the-fly.
.
This includes the GNU
.B .gz
and the traditional
.B .Z
compression.
.
The program displays the concatenation of all decompressed input in
the sequence that was specified on the command line.
.
.
.\" --------------------------------------------------------------------
.SS "Man\~Pages"
.\" --------------------------------------------------------------------
.
The groffer program provides a search facility for system manual pages
(man\~pages).
.
So it can be used as a replacement or a grapical extension for the
.BR man (1)
program.
.
.P
Preformatted man\~pages (cat\~pages) are intentionally not supported,
because groffer is a roff program, not a text pager.
.
With the excellent performance of the actual computers, the
preformatted man\~pages aren't necessary any longer.
.
Due to their inflexible nature, they provoke some trouble with
changing line lengths.
.
These cat\~pages should be disabled with the man\~program, or be
circumvented by using groffer instead.
.
.P
The groffer program determines if the user wanted to diplay a man\~page
by the following methods.
.
If a non-option command line parameter does not represent a valid file
name groffer suspects whether this could be a system manual page
(man\~page).
.
The following parameter formats are recognized to represent a wanted
man\~page.
.
.TP
.IB name . section
the man\~page
.I name
in
.IR section .
The corresponding command with the man program would be
.ShellCommand man \f(CIsection name\fP
.
.TP
.BI man: name ( section )
the quasi-URL notation used in many Desktop systems to 
represent the man\~page
.I name
in
.IR section .
.
.TP
.BI man: name
search the man\~page
.I name
in the lowest section.
The corresponding command with the man program would be
.ShellCommand man \f(CIname\fP
.
.TP
.I name
if
.I name
is not an existing file search for the man\~page
.I name
in the lowest section just like
.ShellCommand man \f(CIname\fP
.
.P
The algorithm for retrieving man\~pages uses five search methods.
.
They are successively tried until a method works.
.
.Topic
The search path can be manually specified by using the option
.LongOpt manpath .
An empty argument disables the man\~page searching.
.
This overwrites the other methods.
.
.Topic
The best results are obtained when the
.BR man (1)
program has the command line option
.ShortOpt w
to determine the path of a man\~page.
.
This is available in the GNU version of
.IR man .
.
.Topic
If this isn't available the environment variable
.EnvVar $MANPATH
is searched.
.
.Topic
If this is empty the
.BR manpath (1)
program for determining a path of man directories is tried.
.
.Topic
If this does not work a reasonable default path is searched for
man\~pages.
.
.P
In all cases, language-specific man\~pages are searched first if the
environment variable
.EnvVar $LANG
is set. 
.
.
.\" --------------------------------------------------------------------
.SS "Source Code"
.\" --------------------------------------------------------------------
.
Usually, groffer displays the input in formatted form.
.
When, however, the option
.ShortOpt Q
is specified on the command line the source code of the input is
displayed instead; more exactly, it is printed onto standard output
as is, without any pager or other formatter.
.
.P
In this source code displaying mode, the decompression and man\~page
search features are still active.
.
As no formatter or X window program is run in this mode all opotions
different from
.ShortOpt Q
are silently ignored.
.
.\" --------------------------------------------------------------------
.SH "ENVIRONMENT"
.\" --------------------------------------------------------------------
.
.TP
.EnvVar $DISPLAY
If this variable is set this indicates that the X window system is
running.
.
Testing this variable decides on whether graphical or text output is
generated.
.
This variable should not be changed by the user carelessly, but it can
be used to start the graphical groffer on a remote X terminal.
.
For example, depending on your system, groffer can be started on the
second monitor by the command
.ShellCommand DISPLAY=:0.1 groffer what.ever &
.
.TP
.EnvVar $PAGER
This variable can be used to set the pager for the tty output.
.
For example, to disable the use of a pager completely set this
variable to the
.BR cat (1)
program
.ShellCommand PAGER=cat groffer anything
.
.TP
.EnvVar $MANPATH
if set, this variable contains the directories in which the man\~page
trees are stored.
.
.TP
.EnvVar $LANG

if set, this variable contains the directories in which the man\~page
trees are stored.
.
.
.\" --------------------------------------------------------------------
.SH "EXAMPLES"
.\" --------------------------------------------------------------------
.
The usage of groffer is very easy.
.
Usually, it is just called with a filename or man\~page.
.
The following examples, however, show that groffer has much more fancy
capabilities.
.
.TP
.ShellCommand groffer docs/meintro.ms
Format and display the file
.I meintro.ms
in directory
.I ./docs
using a graphical viewer when in X window, or the
.B less
pager program when not in X.
.
The file must exist in this case because the slash character
.RB ` / '
suggests that this cannot be a man\~page.
.
.TP
.ShellCommand groffer groffer.1 \[cq]less(1)\[cq] man:roff
.
If none of the arguments is an existing file then lookup the three
man\~pages named
.I groffer
(in section\~1),
.I less
(in section\~1),
and
.I roff
(in the section with the lowest number, being\~7 in this case).
.
The formatted files are concatenated and displayed in one piece.
.
.TP
.ShellCommand LANG=de groffer\~\c
.ShellLongOpt man\~\c
.ShellLongOpt source\~\c
.ShellShortOpt T\~\c
.Text html\~ls\~>ls.html
.
Lookup the source file of the German manual page for the
.B ls
program, decompress it, convert it into htlm format and write the
result into the file
.IR ls.html
.
.TP
.ShellCommand cat stdin.1.gz | PAGER=more groffer\~\c
.ShellLongOpt tty\~\c
.Text a.ms\~\c
.ShellShortOpt \~\c
.Text b.ms.Z
.
Display existing files
.IR a.ms ,
.IR stdin.1.gz (decompress),
and
.IR b.ms.Z (decompress)
in this sequence on the text terminal, using
.BR more
as pager program instead of the default pager
.BR less .
.
.TP
.ShellCommand groffer\~\c
.ShellShortOpt Wno\c
.ShellShortOpt man\~\c
.ShellShortOpt Wtitle=hello\~\c
.ShellShortOpt Wmac\~\c
.Text groff.1
.
Assume that
.I groff.1
is not meant to denote a man\~page, but an existing file
in the current directory.
.
Process this file with the
.RI ` mac '
warnings disabled and display the result using
.RI ` hello '
as the viewer window's title.
.
The first two
.option W
options simulate long options; but as
.I mac
is not a long option for groffer it is passed unchanged to groff,
where it disables the specified warnings.
.
This command is equivalent to
.ShellCommand groffer\~\c
.ShellLongOpt title=hello\~\c
.ShellLongOpt man\~\c
.ShellShortOpt W\~\c
.Text mac groff.7
.
.TP
.ShellCommand echo\~\[rs]fIgroffer\[rs]fP\~is\~\[rs]fBfat\[rs]fP |\&
.TP+
.ShellCommand groffer\~\c
.ShellLongOpt xrdb=\[cq]\c
.ShellShortOpt bg\~\c
.Text red\~\c
.ShellShortOpt fg\~\c
.Text yellow\[cq]
.
This looks a bit strange, try it :\-)
.
.
.\" --------------------------------------------------------------------
.SH "COMPATIBILITY"
.\" --------------------------------------------------------------------
.
The
.B groffer
shell script should be compatible to both POSIX and GNU.
.
POSIX compatibility refers to
.B P1003.2/D11.2
of September 1991.
.
.P
This document describes the behavior on GNU systems.
.
Due to the limitations of POSIX as compared to GNU, not all features
of groffer are available on non-GNU systems.
.
This includes arguments with embedded space characters, and the search
capabilities of man\~pages.
.
.P
The groffer program can handle option arguments and file names that
contain space characters, but mutliple space characters are flattened
to a single space character.
.
.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
.\" --------------------------------------------------------------------
.
.TP
.BR groff (@MAN1EXT@)
the GNU roff program.
.
.TP
.BR grog (@MAN1EXT@)
tries to guess the groff command line options for given input files.
.
.TP
.BR gxditview (@MAN1EXT@)
the GNU version of the roff viewer
.BR xditview (1)
distributed with the the X window system.
.
.TP
.BR gzip (1)
decompression of .gz or .Z files.
.
.TP
.BR man (1)
the standard way to diplay man\~pages.
.
.
.\" --------------------------------------------------------------------
.SH "AUTHORS"
.\" --------------------------------------------------------------------
.
Copyright (C) 2001, 2002 Free Software Foundation, Inc.
.
.P
This document is distributed under the terms of the FDL (GNU Free
Documentation License) version 1.1 or later.
.
You should have received a copy of the FDL on your system, it is also
available on-line at the
.URL http://\:www.gnu.org/\:copyleft/\:fdl.html "GNU copyleft site" .
.
.P
This document is part of
.IR groff ,
the GNU roff distribution.
.
It was written by
.MTO bwarken@mayn.de "Bernd Warken" .
.
.
\" --------------------------------------------------------------------
.\" Emacs settings
.\" --------------------------------------------------------------------
.
.\" Local Variables:
.\" mode: nroff
.\" End:
