.\" Time-stamp: <ShortReference.roff: 30.11.2005 14:49:16 x01 - JWalsdorff@compuserve.de>
.time start
.pv 1.2 1.2 "" x
.H Short Reference for the HDtbl-Macros
This Short Reference shortly describes the Heidelberger Table Macros
using these macros themselves.
.br
.nr t*csp .3n
.nr t*cpd .3n
.ds t*ff HN
.ds t*val m
.ds t*hal l
.xig
.TBL "width=10% 40% 25% 25%" border= "fsz=1 .8"
.CPTN Base- Optional- and Utility-Macros val=b
.TR
.TH Macro .TH Description .TH Predecessors .TH Successors 
.TR 
.TD \&.TBL .TD Begin a new table .TD \&.TD \&.TH \%.ETB cellcontent
.TD \&.CPTN \&.TR 
.TR 
.TD \&.CPTN .TD Optional numbered or unnumbered table caption
.TD \&.TBL .TD \&.TR 
.TR
.TD \&.TR .TD Begin a new table row .TD \&.TBL \&.CPTN cellcontent
.TD \&.TD \&.TR
.TR
.TD \&.TH .TD Optional begin table header cell 
.TD \&.TR \&.TD \&.TH \%.ETB cellcontent
.TD \&.TD \&.TH \&.TR \%.ETB cellcontent
.TR 
.TD \&.TH .TD Begin table data cell .TD \&.TR \&.TD \&.TH \%.ETB cellcontent
.TD \&.TD \&.TH \&.TR \%.ETB cellcontent
.TR 
.TD \&.ETB .TD Finish and pront table. .TD \&.TD \&.TH \%.ETB cellcontent
.TD \&.TBL \&.TR \&.TD \&.TH \%.ETB cellcontent
.TR
.TD \&.t*free 
.TD colspan=3 val=t Utility macro to free held tables. Use it outside any table.
.ETB
.bp
.x.
.TBL "fsz=1 .8" "width=20% 32% 8% 8% 8% 8% 8% 8%" border=
.TR
.TH Argument .TH Value .TH \&.TBL .TH \&.CPT .TH \&.TR .TH \&.TH .TH \&.TD .TH \&.ETB
.TR 
.TD border=\fI[n]\fP 
.TD border thickness .TD .ce X .TD .TD .TD .TD .TD
.TR
.TD bc=\fI[c]\fP 
.TD color of border and cellseperatorlines .TD .ce X .TD .TD .ce X .TD .ce X .TD .ce X .TD
.ETB
.H ------ incomplete -------
.time end