.ig
This file is part of groff, the GNU roff type-setting system.

Copyright (C) 2002 Free Software Foundation, Inc.
written by Werner Lemberg <wl@gnu.org>

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with the
Invariant Sections being this .ig-section and AUTHORS, with no
Front-Cover Texts, and with no Back-Cover Texts.

A copy of the Free Documentation License is included as a file called
FDL in the main directory of the groff source package.
..
.
.mso www.tmac
.
.de TQ
.br
.ns
.TP \\$1
..
.
.TH GROFF_MOM @MAN7EXT@ "@MDATE@" "Groff Version @VERSION@"
.
.
.SH NAME
.
groff_mom \- groff `mom' macros
.
.
.SH SYNOPSIS
.
.B groff
.B \-mom
[
.IR files .\|.\|.\&
]
.br
.B groff
.B \-m\ mom
[
.IR files .\|.\|.\&
]
.
.
.SH DESCRIPTION
.
.B mom
(\[lq]my own macros\[rq], \[lq]my other macros\[rq], \[lq]maximum
overdriver macros\[rq], .\|.\|.\&) is a macro set for groff, designed to
format documents for PostScript output.
.
.
.SH FILES
.TP
.B mom.tmac
.TQ
.B om.tmac
All macros are in the file
.BR om.tmac ;
.B mom.tmac
is a wrapper file which calls
.B om.tmac
directly.
.
.TP
.URL @HTMLDOCDIR@/momdoc/toc.html @HTMLDOCDIR@/momdoc/toc.html
This is the entry point to the HTML documentation of
.BR mom .
.
.TP
.B @EXAMPLEDIR@/*.mom
Example files using
.BR mom .
.
.
.SH AUTHOR
.
.B mom
has been written by
.MTO df191@ncf.ca "Peter Schaffter" ;
please send bug reports
to the
.MTO bug-groff@gnu.org "groff bug mailing list"
or directly to the author.
.
.\" Local Variables:
.\" mode: nroff
.\" End:
