PROG=xtotroff$(EXEEXT)
# MAN1=xtotroff.n
MLIB=$(LIBM)
XLIBS=$(LIBXUTIL)
EXTRA_CFLAGS=$(X_CFLAGS)
EXTRA_LDFLAGS=$(X_LIBS) $(X_PRE_LIBS) -lX11 $(X_EXTRA_LIBS) -lXaw
OBJS=xtotroff.$(OBJEXT)
CSRCS=$(srcdir)/xtotroff.c
