DEV=dvi
DEVFILES=DESC TR TI TB TBI CW CWI MI S EX HR HI HB HBI SA SB \
  generate/CompileFonts generate/Makefile generate/msam.map generate/msbm.map \
  generate/texb.map generate/texex.map generate/texi.map generate/texmi.map \
  generate/texr.map generate/texsy.map generate/textt.map

CLEANADD=DESC

DESC: DESC.in
	cat $(srcdir)/DESC.in >DESC
	test -z '$(DVIPRINT)' || echo print '$(DVIPRINT)' >>DESC
