.TH MMROFF @MAN1EXT@ "@MDATE@" "Groff Version @VERSION@"
.SH NAME
mmroff \- cross reference preprocessor
.
.
.\" --------------------------------------------------------------------
.\" Legalese
.\" --------------------------------------------------------------------
.
.de co
Copyright \(co 1989-2014 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
..
.
.de au
This document was written by
.MT jh@axis.se
Jörgen Hägg, Lund, Sweden
.ME .
..
.
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.
.B mmroff
[
.I \-x
]
.I groff_arguments
.
.
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.
.B mmroff
is a simple preprocessor for
.BR groff ,
it is used for expanding cross references in
.BR m@TMAC_M_PREFIX@m ,
see
.BR groff_mm (@MAN7EXT@).
.
.B groff
is executed twice, first with
.B \-z
and
.B \-rRef=1
to collect all cross references and then to do the real processing
when the cross reference file is up to date.
.
.
.TP
.B \-x
Just create the cross reference file.
.
This can be used to refresh the cross reference file, it isn\(aqt
always needed to have accurate cross references and by using this
option
.B groff
will only be run once.
.
.
.\" --------------------------------------------------------------------
.\".SH BUGS
.\" --------------------------------------------------------------------
.
.
.\" --------------------------------------------------------------------
.SH FILES
.\" --------------------------------------------------------------------
.
.TP
.B @MACRODIR@/@TMAC_M_PREFIX@m.tmac
.TP
.B @TMAC_MDIR@/*.cov
.TP
.B @TMAC_MDIR@/*.MT
.TP
.B @TMAC_MDIR@/locale
.
.
.na
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
.\" --------------------------------------------------------------------
.
.BR groff_mm (@MAN7EXT@),
.BR groff_mmse (@MAN7EXT@),
.BR groff (@MAN1EXT@),
.BR @g@troff (@MAN1EXT@),
.BR @g@tbl (@MAN1EXT@),
.BR @g@pic (@MAN1EXT@),
.BR @g@eqn (@MAN1EXT@)
.
.
.\" --------------------------------------------------------------------
.SH COPYING
.\" --------------------------------------------------------------------
.co
.\" --------------------------------------------------------------------
.SH AUTHORS
.\" --------------------------------------------------------------------
.
.
.
.\" Local Variables:
.\" mode: nroff
.\" coding: latin-1
.\" End:
